apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-pohx
  namespace: somalley-tenant
spec:
  replicas: 2
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:326a88d108b745ed8f497e837a7fa652d87423837c123dbc4917063def89570f
        name: my-go
        resources: {}
status: {}
