apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-2l4s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-2l4s
    app.kubernetes.io/part-of: sotest
  name: devfile-sample-go-basic-2l4s
  namespace: somalley-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic-2l4s
status:
  loadBalancer: {}
